# Header

menu:
  主页: /
  归档: /archives/
  #随笔: /tags/随笔/

# SubNav
subnav:
  github: "https://github.com/dbanote"
  weibo: "http://weibo.com/foxbei"
  #rss: "#"
  #zhihu: "#"
  qq: "http://sighttp.qq.com/msgrd?v=1&uin=9320802"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  mail: "mailto:15004618839@139.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content

# 文章太长，截断按钮文字
# 截断需要在文章中添加 <!--more-->
#excerpt_link: more
excerpt_link: false

# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
#mathjax: true

# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 请在需要打赏的文章的md文件头部，设置属性reward: true

# 打赏基础设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '喜欢的话，支付1元请我吃糖吧！'

# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
# 支付宝收款1元二维码图片
alipay: /img/zhifubao01.png
# 支付宝收款无金额设置二维码图片
# alipay: /img/zhifubao.png

# 微信二维码图片地址
# 微信收款1元二维码图片
weixin: /img/weixin01.png
# 微信收款无金额设置二维码图片
# alipay: /img/weixin.png

# Miscellaneous
baidu_analytics: '2e7a5de312dd959398193e7e92a5cdce'
google_analytics: ''
favicon: /img/favicon.png

#你的头像url
avatar: /img/avatar.jpg

#是否开启分享
share_jia: true

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
#duoshuo: false
duoshuo: dbanote

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false
  

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '常用网站'
  aboutme: '关于我'

friends:
  My Oracle Support: https://support.oracle.com/
  Oracle Edelivery: https://edelivery.oracle.com/
  Oracle Help Center: http://docs.oracle.com/
  练数成金: http://www.dataguru.cn/
  三通IT论坛: http://www.santongit.com/
  一起自学吧: http://www.17zixueba.com/

aboutme: DBA<br><br>工作学习笔记<br>谢谢大家